import express from 'express'; import pg from 'pg'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import cookieParser from 'cookie-parser'; import dotenv from 'dotenv'; import path from 'path'; import {fileURLToPath} from 'url';
dotenv.config(); const {Pool}=pg; const pool=new Pool({connectionString:process.env.DATABASE_URL}); const app=express(); const __dirname=path.dirname(fileURLToPath(import.meta.url)); app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(express.static(__dirname));
const SECRET=process.env.JWT_SECRET; if(!SECRET) throw new Error('JWT_SECRET required');
const sign=u=>jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'8h'});
function auth(req,res,next){try{req.user=jwt.verify(req.cookies.session||'',SECRET);next()}catch{return res.status(401).json({error:'Authentication required'})}}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
function score(l){let s=l.interest==='Hot'?60:l.interest==='Warm'?35:15;if(l.status==='Interested')s+=20;if(l.status==='Thinking')s+=15;if(l.status==='Registered')return 0;if(l.next_followup){let d=Math.ceil((new Date(l.next_followup)-new Date(new Date().toISOString().slice(0,10)))/86400000);if(d<=0)s+=20;else if(d<=2)s+=10}else s+=10;return Math.min(100,s)} const priority=l=>{let s=score(l);return s>=75?'High':s>=45?'Medium':'Low'};
app.post('/api/auth/login',async(req,res)=>{let {email,password}=req.body||{};let r=await pool.query('SELECT * FROM users WHERE lower(email)=lower($1) AND active=true',[email||'']);let u=r.rows[0];if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'Invalid email or password'});res.cookie('session',sign(u),{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:28800000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('session');res.json({ok:true})}); app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/dashboard',auth,async(req,res)=>{let args=req.user.role==='admin'?[]:[req.user.id],where=req.user.role==='admin'?'':'WHERE l.volunteer_id=$1';let r=await pool.query(`SELECT l.*,u.name volunteer_name FROM leads l LEFT JOIN users u ON u.id=l.volunteer_id ${where} ORDER BY l.created_at DESC`,args);let leads=r.rows.map(x=>({...x,score:score(x),priority:priority(x)})).sort((a,b)=>b.score-a.score),today=new Date().toISOString().slice(0,10);res.json({stats:{total:leads.length,high:leads.filter(x=>x.priority==='High').length,due:leads.filter(x=>x.next_followup&&x.next_followup<=today&&x.status!=='Registered').length,registered:leads.filter(x=>x.status==='Registered').length},leads:leads.slice(0,50)})});
app.get('/api/leads',auth,async(req,res)=>{let args=[],c=[];if(req.user.role!=='admin'){args.push(req.user.id);c.push(`l.volunteer_id=$${args.length}`)}if(req.query.q){args.push(`%${req.query.q}%`);c.push(`(l.name ILIKE $${args.length} OR l.phone ILIKE $${args.length} OR l.course ILIKE $${args.length})`)}if(req.query.status){args.push(req.query.status);c.push(`l.status=$${args.length}`)}let r=await pool.query(`SELECT l.*,u.name volunteer_name FROM leads l LEFT JOIN users u ON u.id=l.volunteer_id ${c.length?'WHERE '+c.join(' AND '):''} ORDER BY l.next_followup NULLS LAST,l.created_at DESC`,args);let out=r.rows.map(x=>({...x,score:score(x),priority:priority(x)}));if(req.query.priority)out=out.filter(x=>x.priority===req.query.priority);res.json(out)});
app.post('/api/leads',auth,async(req,res)=>{let d=req.body||{},v=req.user.role==='admin'?d.volunteer_id:req.user.id,r=await pool.query(`INSERT INTO leads(name,phone,course,source,interest,status,batch,volunteer_id,last_contacted,next_followup,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[d.name,String(d.phone||'').replace(/\D/g,''),d.course,d.source||null,d.interest||'Warm',d.status||'Interested',d.batch||null,v||null,d.last_contacted||null,d.next_followup||null,d.notes||null]);res.status(201).json({...r.rows[0],score:score(r.rows[0]),priority:priority(r.rows[0])})});
app.patch('/api/leads/:id',auth,async(req,res)=>{let id=req.params.id,d=req.body||{},e=(await pool.query('SELECT * FROM leads WHERE id=$1',[id])).rows[0];if(!e)return res.status(404).json({error:'Lead not found'});if(req.user.role!=='admin'&&e.volunteer_id!=req.user.id)return res.status(403).json({error:'Not assigned to you'});let fields=['name','phone','course','source','interest','status','batch','volunteer_id','last_contacted','next_followup','notes'],sets=[],args=[];if(req.user.role!=='admin')delete d.volunteer_id;for(let f of fields)if(d[f]!==undefined){args.push(f==='phone'?String(d[f]).replace(/\D/g,''):d[f]);sets.push(`${f}=$${args.length}`)}if(!sets.length)return res.json(e);args.push(id);let r=await pool.query(`UPDATE leads SET ${sets.join(',')},updated_at=NOW() WHERE id=$${args.length} RETURNING *`,args);res.json({...r.rows[0],score:score(r.rows[0]),priority:priority(r.rows[0])})});
app.delete('/api/leads/:id',auth,admin,async(req,res)=>{await pool.query('DELETE FROM leads WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/api/followups/:leadId',auth,async(req,res)=>{let r=await pool.query('SELECT f.*,u.name volunteer_name FROM followups f LEFT JOIN users u ON u.id=f.volunteer_id WHERE f.lead_id=$1 ORDER BY f.created_at DESC',[req.params.leadId]);res.json(r.rows)});
app.post('/api/followups',auth,async(req,res)=>{let d=req.body||{},l=(await pool.query('SELECT * FROM leads WHERE id=$1',[d.lead_id])).rows[0];if(!l)return res.status(404).json({error:'Lead not found'});if(req.user.role!=='admin'&&l.volunteer_id!=req.user.id)return res.status(403).json({error:'Not assigned to you'});let r=await pool.query(`INSERT INTO followups(lead_id,volunteer_id,channel,outcome,note) VALUES($1,$2,$3,$4,$5) RETURNING *`,[d.lead_id,req.user.id,d.channel||'WhatsApp',d.outcome||null,d.note||null]);await pool.query('UPDATE leads SET last_contacted=CURRENT_DATE,updated_at=NOW() WHERE id=$1',[d.lead_id]);res.status(201).json(r.rows[0])});
app.get('/api/volunteers',auth,admin,async(req,res)=>{let r=await pool.query(`SELECT u.id,u.name,u.email,u.active,COUNT(l.id)::int lead_count,COUNT(l.id) FILTER(WHERE l.interest='Hot')::int hot_count FROM users u LEFT JOIN leads l ON l.volunteer_id=u.id WHERE u.role='volunteer' GROUP BY u.id ORDER BY u.name`);res.json(r.rows)});
app.post('/api/volunteers',auth,admin,async(req,res)=>{let {name,email,password}=req.body||{};if(!password||password.length<10)return res.status(400).json({error:'Password must be at least 10 characters'});let h=await bcrypt.hash(password,12);try{let r=await pool.query("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'volunteer') RETURNING id,name,email,role,active",[name,email,h]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'Email already exists'})}});
app.get('/api/templates',auth,async(req,res)=>{let r=await pool.query('SELECT * FROM message_templates WHERE active=true ORDER BY id');res.json(r.rows)});
app.post('/api/messages/queue',auth,async(req,res)=>{let {lead_ids,template_id,body}=req.body||{};if(!Array.isArray(lead_ids)||!lead_ids.length)return res.status(400).json({error:'No leads selected'});let t=null;if(template_id)t=(await pool.query('SELECT * FROM message_templates WHERE id=$1',[template_id])).rows[0];let qs=await pool.query('SELECT * FROM leads WHERE id=ANY($1::bigint[])',[lead_ids.map(Number)]),out=[];for(let l of qs.rows){if(req.user.role!=='admin'&&l.volunteer_id!=req.user.id)continue;let msg=(body||t?.body||'').replaceAll('{{name}}',l.name).replaceAll('{{course}}',l.course).replaceAll('{{batch}}',l.batch||'upcoming batch');let r=await pool.query(`INSERT INTO outbound_messages(lead_id,volunteer_id,template_id,body,status) VALUES($1,$2,$3,$4,'queued') RETURNING id,lead_id,body,status`,[l.id,req.user.id,t?.id||null,msg]);out.push({...r.rows[0],phone:l.phone,name:l.name})}res.status(201).json(out)});
app.get('/health',(req,res)=>res.json({ok:true})); app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Course Tracker running on port '+(process.env.PORT||3000)));
